"""Seed data for the conference demo mode.

When ``settings.demo_mode`` is enabled, ``seed_demo_data`` provisions a single
shared demo user (with completed onboarding preferences) and a handful of sample
trips generated by the real recommendation engine, so the app is usable
end-to-end without registering. Five trips are marked completed and shared to
the community feed; the rest stay active.

It is idempotent: if the demo user already exists it does nothing, so attendee
edits persist across restarts. Generating trips hits the Swiss Tourism API (and
the OpenAI planner when configured); if those aren't available it falls back to
a simple placeholder itinerary so the demo is never empty.
"""

from __future__ import annotations

import asyncio
import logging
from datetime import date
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from app.adapters.sqlalchemy_trip_repo import SqlAlchemyTripRepo
from app.adapters.sqlalchemy_user_repo import SqlAlchemyUserRepo
from app.adapters.swiss_tourism_client import HttpxSwissTourismClient
from app.core.config import settings
from app.core.db import get_public_transport_client
from app.core.security import hash_password
from app.ports.repositories import NewTrip
from app.services.recommendation_service import recommend

logger = logging.getLogger(__name__)

# The Swiss Tourism API rate-limits aggressively, and each recommendation fans
# out to several of its endpoints, so seeding is paced: a pause between trips
# plus retry-with-backoff when a trip is throttled (HTTP 429).
_SEED_DELAY_SECONDS = 5.0
_SEED_MAX_ATTEMPTS = 3
_SEED_RETRY_BACKOFF_SECONDS = 15.0

# Completed-onboarding preferences so the demo user skips the onboarding wizard
# (mirrors hasCompletedOnboarding in frontend/src/preferences.ts).
_DEMO_PREFERENCES: dict[str, Any] = {
    "budget_tier": "mid",
    "pace": "moderate",
    "travel_styles": ["nature_outdoors", "culture_history", "food_markets"],
    "accommodation_types": ["hotel", "boutique"],
    "notes": "Demo account for conference attendees — explore freely!",
}

# Each spec is turned into a real recommendation via the engine. The first five
# are marked completed + shared to the community; the last two stay active.
_DEMO_TRIP_SPECS: list[dict[str, Any]] = [
    {
        "destination": "Zermatt",
        "mood": "nature_outdoors",
        "trip_length": "full_day",
        "start_date": date(2026, 5, 3),
        "completed": True,
        "rating": 5,
        "comment": "The Gornergrat panorama was unreal — 29 peaks in one view.",
    },
    {
        "destination": "Lucerne",
        "mood": "culture_history",
        "trip_length": "half_day",
        "start_date": date(2026, 5, 17),
        "completed": True,
        "rating": 4,
        "comment": "Loved the old town and the lake cruise. Pilatus was a highlight.",
    },
    {
        "destination": "Interlaken",
        "mood": "nature_outdoors",
        "trip_length": "full_day",
        "start_date": date(2026, 5, 24),
        "completed": True,
        "rating": 5,
        "comment": "Jungfraujoch is worth every franc. Bring warm layers!",
    },
    {
        "destination": "Montreux",
        "mood": "food_markets",
        "trip_length": "half_day",
        "start_date": date(2026, 6, 1),
        "completed": True,
        "rating": 4,
        "comment": "Lakeside vineyards and Chillon Castle — a perfect slow day.",
    },
    {
        "destination": "Lugano",
        "mood": "slow_relaxing",
        "trip_length": "half_day",
        "start_date": date(2026, 6, 7),
        "completed": True,
        "rating": 5,
        "comment": "Mediterranean vibes and great gelato. Felt like Italy.",
    },
    {
        "destination": "Zurich",
        "mood": "culture_history",
        "trip_length": "half_day",
        "start_date": date(2026, 7, 18),
        "completed": False,
    },
    {
        "destination": "Lausanne",
        "mood": "culture_history",
        "trip_length": "half_day",
        "start_date": date(2026, 8, 2),
        "completed": False,
    },
]


def _fallback_itinerary(destination: str, start: date) -> dict[str, Any]:
    """Minimal itinerary used when the recommendation engine is unavailable."""
    return {
        "currency": "CHF",
        "estimated_total": 250.0,
        "days": [
            {
                "day": 1,
                "date": start.isoformat(),
                "theme": "Highlights",
                "activities": [
                    {
                        "id": "activity-1-0",
                        "time": "09:30",
                        "title": f"Explore {destination}",
                        "category": "sightseeing",
                        "description": f"Discover the best of {destination}.",
                    },
                    {
                        "id": "activity-1-1",
                        "time": "13:00",
                        "title": "Local lunch",
                        "category": "food_markets",
                        "description": "Regional Swiss specialities.",
                    },
                    {
                        "id": "activity-1-2",
                        "time": "15:30",
                        "title": "Scenic walk",
                        "category": "nature_outdoors",
                        "description": f"A relaxed walk around {destination}.",
                    },
                ],
            }
        ],
    }


async def _generate_trip(spec: dict[str, Any], client, transport) -> dict:
    """Produce {title, destination, description, itinerary} for a trip spec.

    Uses the real recommendation engine when a Swiss Tourism client is
    available; otherwise (or on any failure) returns a placeholder itinerary.
    The LLM planner is intentionally not used for seeding — it occasionally
    returns candidate ids outside the pool (noisy fallback) and adds cost and
    latency. The engine's deterministic planner is reliable and free.
    """
    destination = spec["destination"]
    start = spec["start_date"]
    for attempt in range(1, _SEED_MAX_ATTEMPTS + 1) if client is not None else range(0):
        try:
            recs = await recommend(
                client,
                destination=destination,
                start_date=start,
                end_date=start,
                travelers=2,
                mood=spec["mood"],
                transport_mode="public_transport",
                trip_length=spec["trip_length"],
                group_type="couple",
                budget_tier="mid",
                public_transport_client=transport,
                itinerary_planner=None,
            )
            if recs:
                rec = recs[0]
                return {
                    "title": rec["title"],
                    "destination": rec["destination"],
                    "description": rec["description"],
                    "itinerary": rec["itinerary"],
                }
            logger.warning(
                "Demo seed: no recommendations for %s; using fallback.", destination
            )
            break
        except Exception:
            if attempt < _SEED_MAX_ATTEMPTS:
                wait = _SEED_RETRY_BACKOFF_SECONDS * attempt
                logger.warning(
                    "Demo seed: recommendation failed for %s "
                    "(attempt %d/%d); retrying in %.0fs.",
                    destination,
                    attempt,
                    _SEED_MAX_ATTEMPTS,
                    wait,
                )
                await asyncio.sleep(wait)
            else:
                logger.warning(
                    "Demo seed: recommendation failed for %s after %d attempts; "
                    "using fallback.",
                    destination,
                    _SEED_MAX_ATTEMPTS,
                    exc_info=True,
                )
    return {
        "title": f"{destination} day trip",
        "destination": destination,
        "description": f"A day exploring {destination}.",
        "itinerary": _fallback_itinerary(destination, start),
    }


def _build_clients():
    client = (
        HttpxSwissTourismClient(
            api_key=settings.my_swiss_tourism_api,
            cache_ttl=settings.swiss_tours_cache_ttl,
            offers_cache_ttl=settings.swiss_offers_cache_ttl,
        )
        if settings.my_swiss_tourism_api
        else None
    )
    return client, get_public_transport_client()


async def _populate_trips(session: AsyncSession, user_id: int) -> None:
    client, transport = _build_clients()
    if client is None:
        logger.warning(
            "Demo seed: MY_SWISS_TOURISM_API not set — seeding placeholder trips."
        )

    # Generate sequentially with a pause between trips: the Swiss Tourism API
    # rate-limits aggressively, so we keep one recommendation in flight at a
    # time and space them out.
    trip_repo = SqlAlchemyTripRepo(session)
    for index, spec in enumerate(_DEMO_TRIP_SPECS):
        if index > 0 and client is not None:
            await asyncio.sleep(_SEED_DELAY_SECONDS)
        data = await _generate_trip(spec, client, transport)
        trip = await trip_repo.create(
            NewTrip(
                user_id=user_id,
                title=data["title"],
                destination=data["destination"],
                status="recommended",
                description=data["description"],
                itinerary=data["itinerary"],
            )
        )
        if spec["completed"]:
            await trip_repo.complete(
                trip.id,
                user_id,
                rating=spec["rating"],
                comment=spec["comment"],
                image_urls=[],
            )
            await trip_repo.set_shared(trip.id, user_id, shared=True)


async def seed_demo_data(session: AsyncSession) -> None:
    """Provision the shared demo user and sample trips if not already present."""
    user_repo = SqlAlchemyUserRepo(session)
    if await user_repo.get_by_email(settings.demo_user_email):
        return  # Already seeded — preserve attendee edits.

    user = await user_repo.create(
        email=settings.demo_user_email,
        hashed_password=hash_password(settings.demo_user_password),
        full_name=settings.demo_user_name,
    )
    await user_repo.update_preferences(user.id, _DEMO_PREFERENCES)
    await _populate_trips(session, user.id)


async def reset_demo_trips(session: AsyncSession) -> bool:
    """Delete the demo user's trips and re-generate the sample set.

    Used by the optional manual reset script. Returns False if the demo user
    doesn't exist yet.
    """
    user_repo = SqlAlchemyUserRepo(session)
    user = await user_repo.get_by_email(settings.demo_user_email)
    if not user:
        return False

    trip_repo = SqlAlchemyTripRepo(session)
    for trip in await trip_repo.list_by_user(user.id):
        await trip_repo.delete(trip.id, user.id)

    await _populate_trips(session, user.id)
    return True
